### ISSUE TITLE
Snap distorted; Does not run on mobile

### ISSUE THREAD

**Issue by merlinuwe** [aldrinjenson/obsidian-camera#1]
Hi, thanks for your plugin.

I use a Logitech WebCam with HD1080p. When I make a snap, it is distorted:

![image](https://user-images.githubusercontent.com/4138869/171139769-e5c47713-fb68-4099-9062-7a103edc5a41.png)

(I think, the functionality is not yet available on Android Smartphones, isn't it?)

**Comment by aldrinjenson** [comment]
Hi @merlinuwe ,
I have modified the snap function to use the same dimensions as that of the web cam. 
Can you pull from the latest commit and try once again please.

> (I think, the functionality is not yet available on Android Smartphones, isn't it?)

This plugin was initially developed with just desktop in mind. I tried testing on Android, but the permission APIs were failing to get the videoStream. For now, I've added a file picker in addition which may be helpful in Android.(as in, direct snap is not possible, but you *may* still be able to access camera from the file manager)
Please try both these issues when free and let me know if you have any suggestions. Thanks.

**Comment by merlinuwe** [comment]
Thank you very much, the snaps dimensions are now ok. ;-)

It is possible, to make a photo with your select file ("Datei auswählen") button.

![Screenshot_2022-06-03-19-12-09-428_md obsidian](https://user-images.githubusercontent.com/4138869/171913658-f92872cd-eed9-4b12-bbe7-be5f569f5204.jpg)

But sadly, I cannot add videos, as you said in your comment. Is a workaround possible?

**Comment by aldrinjenson** [comment]
Hi, I missed the video aspect initially, but I've added it now.
I have also hidden the unnecessary buttons in mobile view when the permission denied error occurs.

**Comment by aldrinjenson** [comment]
Hi, since the problems mentioned have been fixed, I'm closing this.
