### ISSUE TITLE
2 Links instead of only 1

### ISSUE THREAD

**Issue by merlinuwe** [aldrinjenson/obsidian-camera#3]
When I make a camera clip (Win 10), it is inserted twice in the note:

![image](https://user-images.githubusercontent.com/4138869/172438371-c8cac44d-7771-4e4a-bcf2-205773c03cf6.png)

(In the folder it is only once stored.)

**Comment by aldrinjenson** [comment]
Can you clarify the following please:
- Does this happen always or only on some occasions like maybe when the video is really large?
- Does this happen only for camera recordings and not when you're uploading the file using the file picker?
- Have you noticed this issue on any platform other than Windows?

**Comment by merlinuwe** [comment]
Hi Aldrin,

it has occured only twice (see screenshot). I cannot reproduce it.
Yes the problem was only by camera recordings. The clip was really short (~a few seconds). (Images had no problem.)
I only use obsidian with windows 10 (and android 11).

HTH

Uwe

**Comment by merlinuwe** [comment]
Today with 1.2.1 I can reproduce it again (Win10) even after a restart of obsidian.

![image](https://user-images.githubusercontent.com/4138869/173304097-ed67a2ca-f4c2-49ff-8db3-968197e393d1.png)

**Comment by aldrinjenson** [comment]
Hi, can't reproduce this. Must be due to some other extension of yours conflicting..
