### ISSUE TITLE
Android mobile allows only film, not image

### ISSUE THREAD

**Issue by merlinuwe** [aldrinjenson/obsidian-camera#4]
A few releases before, it was only possible to insert an image. Now it is only possible to insert a film clip. ;-)
(But cool: You've found a way!)

 (Huawei Poco X3 Pro)

**Comment by aldrinjenson** [comment]
Hi, are you on the latest version(1.1.0 as of now)? 
I'm afraid I'm not able to re-create the issue. Just tested on Android 11 and with the latest release, it's possible to add both images and videos.
Would you be able to provide some more details..like, maybe what was the file extension you were trying to import, OS version etc.

**Comment by aldrinjenson** [comment]
Hi @merlinuwe , Obsidian-camera is my first ever Obsidian plugin.
Maybe it's my lack of past experience in this field, but accessing video stream in mobile proved extremely challenging as different versions of mobile seems to interpret the input field in different ways. Even, testing a new change meant, manually copy pasting files first through usb to one folder and then using the phone's file manager to move it to the hidden .obsidian/plugins... folder. 

Anyways, sorry for the delay, but for now, as a workaround, I've added 2 file pickers. The first one will let you access video stream and the second one is for taking a picture. From the 2 mobiles I've tested on, you can switch cameras(front and back) in both video and image captures. I've still got to figure out how to make the text in these pickers different, but for the now the functionality works🤞. 
Please try updating to the latest release (1.2.0) and see if this helps. Thanks.
