### ISSUE TITLE
"Failed to install plugin "Obsidian Camera". on iOS

### ISSUE THREAD

**Issue by noenfugler** [aldrinjenson/obsidian-camera#5]
Receive the following error message when attempting to install the obsidian-camera plugin via the community plugins page Obsidian on iOS.
"Failed to install plugin "Obsidian Camera".

iOs 15.4.1
Model Name iPhone XR
Vault is on iCloud
obsidian-camera version 1.1.0

Able to successfully install and enable on Macos Monterey.  Was then able to access on iOS once synchronised.

**Comment by aldrinjenson** [comment]
Hi, thanks for reporting this. 
Unfortunately, I'm not having any Apple devices at the moment to test this out. 
And, I'm not aware of an easy way to get logs from iOS as well.
Let's leave the issue open so that hopefully someone else in the future may be able to provide some insight.🤞

**Comment by Jopp-gh** [comment]
Same on Android, can't install it on android version 12
![Screenshot_20220611-154900](https://user-images.githubusercontent.com/48620536/173190722-99cd2e69-8bb1-4cd8-83b7-a75296a91a2c.png)

**Comment by Jopp-gh** [comment]
I installed manually, now I can register videos if i click the gray button "choose file" 
That's cool, but often i just wanna add pictures -  switching to camera doesn't work because "getVideoStream" isn't supported for my device 😕

![IMG_20220611_161218](https://user-images.githubusercontent.com/48620536/173191428-2bde9f87-a278-44b0-83fe-0269da551119.png)

**Comment by SR023** [comment]
macos 14 too, show "plugin id is mismatch"

**Comment by aldrinjenson** [comment]
Hi, can you please update to the latest release (1.2.0) and see if it's fixed.
I couldn't test on iOS, but I've made some changes which should get the pluginID mismatch error go away.

**Comment by aldrinjenson** [comment]
> That's cool, but often i just wanna add pictures - switching to camera doesn't work because "getVideoStream" isn't supported for my device 😕

@johans3 , in the latest release, as a workaround I've added 2 file pickers which should let you choose b/w images and videos.  I don't have much experience in building plugins, but please see if it helps. I'll make the text appear different in a later release once I figure out how to do so, but for now, just keep in mind that the first picker is for selecting videos and the second one is for images.

**Comment by Jopp-gh** [comment]
Works great! @aldrinjenson 
The only thing that needs a little tweak are the strings on and beside the buttons, please see attachment. The button says , _choose file_ for both camera and video and the strings aside says, _nothing selected_ . I'd suggest to remove the strings aside and center the buttons, maybe a svg icon could do the job a well (for camera / video) so clicking gets even more intuitive

![IMG_20220614_114825](https://user-images.githubusercontent.com/48620536/173549025-c6521081-ff5c-4d97-8586-eb15ec00620a.png)

**Comment by aldrinjenson** [comment]
Hey @johans3 , I'm moving the renaming issue to it's own separate thread #11 and am closing this one.
Feel free to subscribe to that thread.
Hopefully it'll get fixed soon.
