### ISSUE TITLE
Request - select other camera (back facing)

### ISSUE THREAD

**Issue by genmce** [aldrinjenson/obsidian-camera#6]
Not an issue, a request for selection of camera. 
iPhone has two cameras - please a way to choose which camera captures. Thank you for the plug-in!

**Comment by aldrinjenson** [comment]
Hi @genmce , I have added a switch camera button in a previous release which may help resolve this issue. I do not have an iPhone to verify this though. The button will come visible (only) if there are more than 1 cameras detected.
However, please note that the plugin was made for obsidian-desktop primarily and may not work as expected in all mobile devices.
Hope you understand. Thank You.

Closing this one. Feel free to re-open it if necessary.
