### ISSUE TITLE
The Webcam doesn't close. 😲 It keeps showing a little light, it means it's on, even when Obsidian is minimised or Plugin is disabled.

### ISSUE THREAD

**Issue by ManasMadrecha** [aldrinjenson/obsidian-camera#7]

**Comment by ManasMadrecha** [comment]
Disable the plugin, and the light is still there. 

Tried to open the Camera using normal Windows app, and this is what is shows. 

![image](https://user-images.githubusercontent.com/65993481/173202771-910d3f40-02bc-498c-80c8-0e6479f616c9.png)

**Comment by La5erHyperkubez** [comment]
Check and see if you created a button for it.

**Comment by aldrinjenson** [comment]
Sorry for the delay folks.
Couldn't figure out how to fix this earlier. But now it has been resolved in the latest release.
