### ISSUE TITLE
Switch Camera has no effect

### ISSUE THREAD

**Issue by merlinuwe** [aldrinjenson/obsidian-camera#9]
Release 1.2.1, Win10: The button "Switch camera" has no effect. This may be because I only have one camera available.
Suggestion for a notification window: "There is only one camera, so nothing can be switched."

(Perhaps you can show, which camera is currently connected?)

**Comment by aldrinjenson** [comment]
It has been made such that the switch camera button is shown only if there are more than one cameras present.
